### PR TITLE
Add fuzzing, fix panics

### LINKED ISSUE #22: Panic with malformed template {#}
Reproduction:

```rust
fn main() {
    let data = "{#}";

    let mut tpl = tinytemplate::TinyTemplate::new();

    let _ = tpl.add_template("template", data);
}
```

Gives

```
thread 'main' panicked at 'begin <= end (2 <= 1) when slicing `{#}`', /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tinytemplate-1.2.1/src/compiler.rs:59:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/952fdf2a1119affa1b37bcacb0c49cf9f0168ac8/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/952fdf2a1119affa1b37bcacb0c49cf9f0168ac8/library/core/src/panicking.rs:92:14
   2: core::str::slice_error_fail
   3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/952fdf2a1119affa1b37bcacb0c49cf9f0168ac8/library/core/src/str/traits.rs:214:21
   4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/952fdf2a1119affa1b37bcacb0c49cf9f0168ac8/library/core/src/str/traits.rs:64:9
   5: tinytemplate::compiler::TemplateCompiler::compile
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tinytemplate-1.2.1/src/compiler.rs:59:31
   6: tinytemplate::template::Template::compile
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tinytemplate-1.2.1/src/template.rs:124:27
   7: tinytemplate::TinyTemplate::add_template
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tinytemplate-1.2.1/src/lib.rs:189:24
   8: scratchPpQmmMhHJ::main
             at ./main.rs:6:13
   9: core::ops::function::FnOnce::call_once
             at /rustc/952fdf2a1119affa1b37bcacb0c49cf9f0168ac8/library/core/src/ops/function.rs:227:5
```

I'll make a PR to add the fuzzing harness I used to find this, so you can run it yourself with [`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz).

### PR DESCRIPTION
**Pull request by 197g**
Based on #23 but also fixes all panics found via such fuzzing. These are essentially already found in issues.

Closes: #22
Closes one other panic in malformed templates: An input ending in a literal with escape `\` would reenter the parsing loop another time with empty input and `escaped` set, but `conume_text` assumes at least one byte to be present when escaped is set.

### CODE REVIEW

File: src/compiler.rs [hunk 1]
```diff
@@ -342,9 +349,11 @@ impl<'template> TemplateCompiler<'template> {
     /// (including the expected_close characters), or return an error message if we reach the end
     /// of a line of text without finding it.
     fn consume_tag(&mut self, expected_close: &str) -> Result<&'template str> {
+        let start_len = expected_close.len();
```
Comment (bheisler) [inline src/compiler.rs:352]: This confused me until I read the commit message that explained that we're assuming the start of the tag is the same length as the end of the tag. Could you add a comment here to clarify that?

**Comment by bheisler** [comment]
Hey, thanks for the pull request. 

I'd never really considered fuzzing this code since the templates are typically compiled into the executable (ie. hopefully not attacker-controlled) and therefore not security-sensitive. These are problems that a regular user might run into though, so thanks for doing the legwork for me.

In addition to the one request for a comment, could you add a couple of regular unit tests to demonstrate the erroneous cases the fuzzer found? Thanks!

**Comment by HeroicKatora** [comment]
That should have addressed everything. Can you give it another review?

**Comment by bheisler** [comment]
Thanks for the pull request!
